ALTER TABLE deliveries
  ADD COLUMN IF NOT EXISTS quantity INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS purchase_amount BIGINT,
  ADD COLUMN IF NOT EXISTS is_direct_buy BOOLEAN NOT NULL DEFAULT FALSE;
